name: Deploy Go Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: gustrb.xyz
        username: ubuntu
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /var/www/gustrb.xyz
          docker-compose down
          docker-compose build
          docker-compose up -d
