name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: gustrb.xyz
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/www/gustrb.xyz
            git pull origin main
            sudo systemctl reload nginx

